### ISSUE TITLE
Mate Applet : compiles but does not execute with Gtk-ERROR

### ISSUE THREAD

**Issue by ghost** [equeim/snw-plugin#1]
The applet build for mate is compiled sucsessfully but when tried to launch gives the error : 
(snw-applet:1933): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported . 
Using: Mate 1.16 GTK3
OS: Manjaro (Arch based)

**Comment by equeim** [comment]
Do you use GTK+3 version of mate-panel? snw-applet supports only GTK+2.

**Comment by ghost** [comment]
Yes ! stated in the issue . Is there any plan to port it to Gtk 3 since Mate is droping more and more gtk2 with releases ?

**Comment by equeim** [comment]
Yes, I will add support of gtk3 in future.

**Comment by ghost** [comment]
Thank you very much ! Issue solved
